### ISSUE TITLE
Invalid in-game invite link

### ISSUE THREAD

**Issue by JohnSmith777779** [SpitfireMk2b-san/rinsimulator#1]
The box at the end of the game links to [https://discord.com/invite/kvtVBnC](https://discord.com/invite/kvtVBnC). However, the in-game button and going to the link manually both take me to the Discord poop of death (invalid invite page). The page in the readme works; it's just the in-game link that's messed up. 

~~I don't know how to do a pull request.~~ Was that pull request done correctly?

![invalid](https://user-images.githubusercontent.com/68935009/94068544-53839500-fdbd-11ea-9b80-4342e069f170.PNG)

**Comment by SpitfireMk2b-san** [comment]
I didn't even see this until just now lol, I'll fix this in the next version. Thanks for letting me know!
